Display intent filters of activities, services and broadcast receivers
xgouchet/Stanley pull request #52
Opened 2020-10-12 11:01 UTC by ekrmh

**Fix** #51

### Solution
According my research we can not obtain intent filters from package manager. Hence currently parsing AndroidManifest.xml file is a only solution to obtain intent-filters.
[Google Issue Tracker - Support PackageManager.GET_INTENT_FILTERS](https://issuetracker.google.com/issues/36908355)

This PR parses the AndroidManifest.xml file, obtain intent-filters of  activities, services and broadcast receivers and display them in the app detail page.

### Test
![Screenshot_20201012_134606_fr xgouchet packageexplorer debug](https://user-images.githubusercontent.com/20462900/95738206-84a30700-0c91-11eb-86e4-885077b3af2a.jpg)

2020-10-13 07:50 UTC, xgouchet commented
Overall nice work, thanks @ekrmh 
My main concern with this implementation is that the whole information is combined in a single text view, meaning that we loose clarity, and the automatic copy to clipboard on tap copies the whole thing, which makes it useless.
I'm ok with your approach of displaying the data itself, but maybe you can add one item per intent filter. Another approach would be to add an action with a ➕  icon on activities, services etc… and open a new screen to get the details about the intent filters and meta data for that specific component.

2020-10-13 10:18 UTC, ekrmh commented
@xgouchet Thanks for the comment. I understood your concern. In my opinion, displaying intent filters one by one will be better approach than displaying them in a new screen. I will update PR and show the intent filters one by one on the detail screen if appropriate for you and they will be copyable.

2020-10-14 06:17 UTC, xgouchet requested changes

2020-10-14 06:17 UTC, xgouchet commented on app/src/main/java/fr/xgouchet/packageexplorer/details/DetailsSource.kt
> +                onNext(AppInfoWithSubtitle(AppInfoType.INFO_TYPE_SERVICES, simplifiedName, "", service.name))
If you leave the `subtitle` blank, you should use the `AppInfoSimple` type instead.

2020-10-14 06:17 UTC, xgouchet commented on app/src/main/java/fr/xgouchet/packageexplorer/details/DetailsSource.kt
> +    private fun extractIntentFilters(observableEmitter: ObservableEmitter<AppInfoViewModel>, packageInfo: PackageInfo, tagName: String, nameValue: String) {
Every time you run the method, you're exporting and parsing the same xml files, meaning that if an application uses a large number of activities and services, you're gonna parse the XML file a 100 times.

2020-10-14 06:17 UTC, xgouchet commented on app/src/main/java/fr/xgouchet/packageexplorer/details/DetailsSource.kt
> +    private fun extractIntentFilters(observableEmitter: ObservableEmitter<AppInfoViewModel>, packageInfo: PackageInfo, tagName: String, nameValue: String) {
Also you're missing a few information that do exist in the manifest : 
- intent-filter
    - `android:icon`
    - `android:label`
    - `android:priority`
- data
    - you're missing the type of data, you're only displaying the value

2020-10-15 15:12 UTC, ekrmh commented on app/src/main/java/fr/xgouchet/packageexplorer/details/DetailsSource.kt
> +                onNext(AppInfoWithSubtitle(AppInfoType.INFO_TYPE_SERVICES, simplifiedName, "", service.name))
AppInfoWithSubtitle changed to AppInfoSimple

2020-10-15 15:14 UTC, ekrmh commented on app/src/main/java/fr/xgouchet/packageexplorer/details/DetailsSource.kt
> +    private fun extractIntentFilters(observableEmitter: ObservableEmitter<AppInfoViewModel>, packageInfo: PackageInfo, tagName: String, nameValue: String) {
- Displayed missing informations (icon, label, priority, type etc. ).

- AndroidManifest.xml file exported and parsed only one time.

2020-10-15 15:46 UTC, xgouchet requested changes
Nice work, just two quick requests and then it'll be good to go!

2020-10-15 15:46 UTC, xgouchet commented on app/src/main/java/fr/xgouchet/packageexplorer/details/app/AppDetailsSource.kt
> +            androidManifestXml = exportManifestDomFromPackage(packageInfo).parseDocumentToManifest()
If you do it there, you also need to do the same mechanism for the `APKDetailsSource` (i.e. the source when reading info from an APK file instead of an installed app).

2020-10-15 15:46 UTC, xgouchet commented on app/src/main/res/layout/item_info_bullet.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
nice work, it'd be nice to have a clear separator between the name and value (it could be as simple as having an `=` sign between the two text views)

2020-10-15 16:13 UTC, ekrmh commented on app/src/main/java/fr/xgouchet/packageexplorer/details/app/AppDetailsSource.kt
> +            androidManifestXml = exportManifestDomFromPackage(packageInfo).parseDocumentToManifest()
AndroidManifest file for ApkDetailsSource has been parsed.

2020-10-15 16:14 UTC, ekrmh commented on app/src/main/res/layout/item_info_bullet.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Separator textview added to BulletViewHolder

2020-10-15 16:32 UTC, xgouchet approved these changes
Very nice work @ekrmh , thanks a lot

2020-10-15 16:38 UTC, merged

2020-10-15 16:54 UTC, ekrmh commented
@xgouchet Thanks, I would like to contribute more.